name: sports
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_html: ^2.2.1
  image_picker: ^0.8.6
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.1
  cloud_firestore: ^4.0.1
  firebase_storage: ^11.0.1
  cupertino_icons: ^1.0.5
  page_transition: ^2.0.9
  cached_network_image: ^3.2.2
  url_launcher: ^6.1.6
  provider: ^6.0.4
  intl: ^0.17.0
  flutter_slidable: ^2.0.0
  loading_indicator: ^3.1.0
  pull_to_refresh: ^2.0.0
  awesome_dialog: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
