name: sports
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_html: ^2.2.1
  image_picker: ^0.8.6
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.1
  cloud_firestore: ^4.0.1
  firebase_storage: ^11.0.1
  flutter_native_splash: ^2.2.0+1
  cupertino_icons: ^1.0.5
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
